---
- name: "Make sure mongod symlink exists"
  file:
    src: '{{ mongod_path }}'
    dest: '{{ unifi_install_destination }}/UniFi/bin/mongod'
    state: link

- name: "Deploy unifi.service.j2 template"
  become: yes
  template: 
    src: unifi.service.j2
    dest: /etc/systemd/system/unifi.service
    mode: 644

- name: "Make sure data directory exist"
  become: yes
  file:
    dest: '{{ unifi_install_destination }}/UniFi/data'
    state: directory
    owner: '{{ unifi_user }}'

- name: "Deploy config.properties.j2 template if not present"
  become: yes
  template:
    src: system.properties.j2
    dest: '{{ unifi_install_destination }}/UniFi/data/system.properties'
    owner: '{{ unifi_user }}'
    force: no

- name: "Enable and start unifi service"
  become: yes
  service:
    name: unifi.service
    enabled: yes
    state: started
